### ISSUE TITLE
自己的数据集做好了之后，修改了alphabets，运行的时候出现这个错误，是怎么回事呢？

### ISSUE THREAD

**Issue by WJinhai** [Sierkinhane/crnn_chinese_characters_rec#100]
Traceback (most recent call last):
  File "/home/weijava/crnn_chinese_characters_rec-master/crnn_main.py", line 195, in <module>
    training(crnn,train_loader,criterion,optimizer)
  File "/home/weijava/crnn_chinese_characters_rec-master/crnn_main.py", line 110, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "/home/weijava/crnn_chinese_characters_rec-master/crnn_main.py", line 88, in trainBatch
    utils.loadData(image, cpu_images)
  File "/home/weijava/crnn_chinese_characters_rec-master/utils.py", line 186, in loadData
    v.data.resize_(data.size()).copy_(data)
RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()

**Comment by XiaXuehai** [comment]
v.data.resize_(data.size()).copy_(data) 修改为 v.resize_(data.size()).copy_(data)试试

**Comment by czzbb** [comment]
请问下是不是如果换一个数据集的话只要换一个alpahbets？另外如果是的话，alpahbets要怎么生成呢？

**Comment by FLming** [comment]
你的pytorch版本是1.0以上吧？api改了。
def loadData(v, data):
    with torch.no_grad():
        v.resize_(data.size()).copy_(data)
改成这样。ctcloss用自带的就行

**Comment by gregar1226** [comment]
@FLming 
你好，可是我改了依然報錯
pytorch版本1.1
