### ISSUE TITLE
Traceback (most recent call last):   File "crnn_main.py", line 195, in <module>     training(crnn,train_loader,criterion,optimizer)   File "crnn_main.py", line 110, in training     cost = trainBatch(crnn, criterion, optimizer, train_iter)   File "crnn_main.py", line 88, in trainBatch     utils.loadData(image, cpu_images)   File "/home/zcyang/crnn_chinese_characters_rec-master/utils.py", line 186, in loadData     v.data.resize_(data.size()).copy_(data) RuntimeError: set_sizes_contiguous is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by zhangchunyang1995** [Sierkinhane/CRNN_Chinese_Characters_Rec#117]

**Comment by axia75** [comment]
pytorch 1.10 版本这个data.resize_(data.size()).copy_(data) 已经被改了 百度一下可以查到有人回答了这个问题

**Comment by niddal-imam** [comment]
Use this v.resize_(data.size()).copy_(data). It works for me.
