### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by MarStarck** [Sierkinhane/crnn_chinese_characters_rec#12]
```
loading pretrained model from trained_models/mixed_second_finetune_acc97p7.pth
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    crnn_recognition(image, model)
  File "test.py", line 56, in crnn_recognition
    print('results: {0}'.format(sim_pred))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-46: ordinal not in range(128)
```

**Comment by Sierkinhane** [comment]
试一下在test.py 顶部加上这两行代码
import sys 
sys.setdefaultencoding('utf-8')

**Comment by MarStarck** [comment]
@Sierkinhane 看起来是我linux系统不能显示中文的缘故QAQ
ps，你有没有遇到过loss一直是0的问题？

**Comment by haneSier** [comment]
没有呢检查一下数据，代码应该没问题

**Comment by MarStarck** [comment]
我换成cpu不使用cuda就能正常训练了，虽然慢了点，但现在精度已经89%
非常好的工作！
