### ISSUE TITLE
crnn_main.py训练时，utils.py报错：UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 2: invalid continuation byte

### ISSUE THREAD

**Issue by gujiachen** [Sierkinhane/crnn_chinese_characters_rec#121]
Traceback (most recent call last):
  File "crnn_main.py", line 195, in <module>
    training(crnn,train_loader,criterion,optimizer)
  File "crnn_main.py", line 110, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "crnn_main.py", line 89, in trainBatch
    t, l = converter.encode(cpu_texts)
  File "/crnn/crnn_chinese_characters_rec-master/utils.py", line 79, in encode
    item = item.decode('utf-8','strict')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 2: invalid continuation byte

**Comment by chenzh12** [comment]
你好，我在训练数据的时候也遇到这个问题，请问你解决了吗，是怎么解决的？

**Comment by gujiachen** [comment]
数据集生成的时候有错误，你检查一下train.txt中是否有特殊字符
