### ISSUE TITLE
自建数据集出现错误cv2.error

### ISSUE THREAD

**Issue by kartherion** [Sierkinhane/crnn_chinese_characters_rec#142]
出现如下错误：
Traceback (most recent call last):
  File "crnn_main_v2.py", line 187, in <module>
    main(crnn, train_loader, val_loader, criterion, optimizer)
  File "crnn_main_v2.py", line 117, in main
    train(crnn, train_loader, criterion, Iteration)
  File "crnn_main_v2.py", line 90, in train
    for i_batch, (image, index) in enumerate(train_loader):
  File "/home/klwang/Software/anaconda2/envs/tf3-gpu1.8/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/klwang/Software/anaconda2/envs/tf3-gpu1.8/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/klwang/Software/anaconda2/envs/tf3-gpu1.8/lib/python3.5/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/klwang/Software/anaconda2/envs/tf3-gpu1.8/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/klwang/Software/anaconda2/envs/tf3-gpu1.8/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/klwang/Software/anaconda2/envs/tf3-gpu1.8/lib/python3.5/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/klwang/download/crnn_chinese_characters_rec/dataset_v2.py", line 65, in __getitem__
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
大概是哪里出问题了？

**Comment by MTCai** [comment]
检查train.txt和test.txt的编码格式，需要是utf-8格式，你用代码打印输出txt第一行，看看开头是不是有多余字符。

**Comment by kartherion** [comment]
> 这种情况一般是没有读到图，一般是路径错误。检查train.txt和test.txt的编码格式，需要是utf-8格式，你用代码打印输出txt第一行，看看开头是不是有多余字符。

感谢回复，经查是我数据的问题．

**Comment by 1261017506** [comment]
为什么我用github上面下载的txt，有这个问题

**Comment by wwzh2015** [comment]
> > 这种情况一般是没有读到图，一般是路径错误。检查train.txt和test.txt的编码格式，需要是utf-8格式，你用代码打印输出txt第一行，看看开头是不是有多余字符。
> 
> 感谢回复，经查是我数据的问题．

请问怎么解决？我的路径没问题，但是还是这样（own txt已经改为utf-8保存）

**Comment by zcswdt** [comment]
这个问题有解决方法了吗，哪个大佬可以分享一下？

**Comment by zcswdt** [comment]
> 这种情况一般是没有读到图，一般是路径错误。检查train.txt和test.txt的编码格式，需要是utf-8格式，你用代码打印输出txt第一行，看看开头是不是有多余字符。

已经解决，确实是.txt文档编码问题，用notepad++打开文档，改一下utf-8格式编码，保存即可。多谢！
