### ISSUE TITLE
训练出问题

### ISSUE THREAD

**Issue by Lemonyue** [Sierkinhane/crnn_chinese_characters_rec#15]
为什么每训练一段时间，就会周期性出现如下错误，但是不影响训练进程
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa67ff97f60>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 345, in get
    return ForkingPickler.loads(res)
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.5/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 737, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by Sierkinhane** [comment]
你设置了多少进程（就是param.py 里面的workers）， 你这个错误应该和线程、进程有关

**Comment by Lemonyue** [comment]
用的默认的2

**Comment by Lemonyue** [comment]
训练完成后又出现这个错误
Traceback (most recent call last):
  File "crnn_main.py", line 183, in <module>
    training()
  File "crnn_main.py", line 115, in training
    torch.save(crnn.state_dict(), '{0}/crnn_Rec_done_{1}_{2}.pth'.format(params.experiment, total_steps, i))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 132, in _with_file_like
    f = open(f, mode)
FileNotFoundError: [Errno 2] No such file or directory: './expr/crnn_Rec_done_1_204976.pth'

**Comment by Lemonyue** [comment]
没有呢

**Comment by hongminli** [comment]
训练时为什么LOSS是0，我用的cuda

**Comment by Sierkinhane** [comment]
检查一下数据集

**Comment by elena9243** [comment]
> 训练时为什么LOSS是0，我用的cuda

解决了吗？我也遇到这个问题，求教

**Comment by tianxingyzxq** [comment]
我也遇到同样的问题，数据集怎么检查呢？用的就是3.6 million chinese characters dataset

**Comment by haneSier** [comment]
调整下学习率看看，

**Comment by wangshuai66666** [comment]
好好检测一些自己的alphabets.py 字典里的内容，如果有重复的就会报这个错误，我自己写个python去检查过滤一下alphabets.py里的所有内容，就不报这个错误了。
