### ISSUE TITLE
可以问一下这是啥问题吗

### ISSUE THREAD

**Issue by 1920853199** [Sierkinhane/crnn_chinese_characters_rec#166]
```
[root@10-9-110-141 crnn_chinese_characters_rec]# python3 crnn_main.py
Traceback (most recent call last):
  File "crnn_main.py", line 195, in <module>
    training(crnn,train_loader,criterion,optimizer)
  File "crnn_main.py", line 110, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "crnn_main.py", line 85, in trainBatch
    data = train_iter.next()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/python/crnn_chinese_characters_rec/dataset.py", line 50, in __getitem__
    buf.write(imgbuf)
TypeError: a bytes-like object is required, not 'NoneType'
<hr>

```

**Comment by yerui2018** [comment]
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from

Log中不是有这个提示嘛

**Comment by 1920853199** [comment]
解决了,因为训练图片的数量问题。可以通过改配置文件解决

**Comment by mrlihellohorld** [comment]
请问您具体是怎么解决的呢，我也遇到这个问题了
