### ISSUE TITLE
怎么老是 读不到图片？

### ISSUE THREAD

**Issue by wwzh2015** [Sierkinhane/crnn_chinese_characters_rec#199]
load 12 images!
load 6 images!
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main()
  File "train.py", line 112, in main
    function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
  File "F:\CRNN_Chinese_Characters_Rec-stable\lib\core\function.py", line 36, in train
    for i, (inp, idx) in enumerate(train_loader):
  File "C:\ProgramData\Anaconda3\envs\crnn\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "C:\ProgramData\Anaconda3\envs\crnn\lib\site-packages\torch\utils\data\dataloader.py", line 846, in _process_data
    data.reraise()
  File "C:\ProgramData\Anaconda3\envs\crnn\lib\site-packages\torch\_utils.py", line 369, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\crnn\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\ProgramData\Anaconda3\envs\crnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\crnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\CRNN_Chinese_Characters_Rec-stable\lib\dataset\_own.py", line 36, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by Sierkinhane** [comment]
检查一下路径吧

**Comment by wwzh2015** [comment]
> 检查一下路径吧

我确定路径没错

**Comment by wwzh2015** [comment]
已解决
