### ISSUE TITLE
KeyError: '鎴'

### ISSUE THREAD

**Issue by zhangchunyang1995** [Sierkinhane/crnn_chinese_characters_rec#200]
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    main()
  File "train.py", line 112, in main
    function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
  File "/home/zhangchunyang/CRNN_Chinese_Characters_Rec/lib/core/function.py", line 48, in train
    text, length = converter.encode(labels)
  File "/home/zhangchunyang/CRNN_Chinese_Characters_Rec/lib/utils/utils.py", line 109, in encode
    index = self.dict[char]
KeyError: '鎴'

**Comment by Sierkinhane** [comment]
将这个字加到alphabet里面去

**Comment by JwDong2019** [comment]
您好，我也是使用了Chinese OCR数据集，用的是999999张图那部分，和你出现了同样的问题，你是具体怎么解决的呢？
