### ISSUE TITLE
我修改了alphabet = """Σ:平累谷峰0123456789.t"""，训练报错

### ISSUE THREAD

**Issue by wwzh2015** [Sierkinhane/crnn_chinese_characters_rec#203]
数据集很简单，就这几个字符，用原来的alphabet 全是错字，而且准确率始终为零
所以我修改精简了alphabet，现在训练报错：
 Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 111, in main
    function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
  File "F:\CRNN_Chinese_Characters_Rec-stable\lib\core\function.py", line 48, in train
    text, length = converter.encode(labels)
  File "F:\CRNN_Chinese_Characters_Rec-stable\lib\utils\utils.py", line 109, in encode
    index = self.dict[char]
KeyError: '：

这是什么原因？

**Comment by Sierkinhane** [comment]
字典里加上 '  这个字符
