### ISSUE TITLE
加载模型训练出错

### ISSUE THREAD

**Issue by Waynepoo** [Sierkinhane/crnn_chinese_characters_rec#215]
加载作者给的模型报下面错误：
train.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
=> creating output/360CC/crnn/2020-05-13-01-31/checkpoints
=> creating output/360CC/crnn/2020-05-13-01-31/log
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 75, in main
    model.load_state_dict(checkpoint['state_dict'])
KeyError: 'state_dict'

加载自己训练的模型也会报错（acc一直是0，所以想在作者模型的基础上继续训练）：
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 81, in main
    config.TRAIN.LR_FACTOR, last_epoch-1
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 382, in __init__
    super(MultiStepLR, self).__init__(optimizer, last_epoch)
  File "/opt/conda/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 41, in __init__
    "in param_groups[{}] when resuming an optimizer".format(i))
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"
在train.py 81行修改了指定的epoch还是没用，能帮忙看看吗

**Comment by Sierkinhane** [comment]
model.load_state_dict(checkpoint['state_dict']) 去掉 state_dict

**Comment by Sierkinhane** [comment]
如果要resume一个optimizer，先定义一个optimizer再resume，过段时间我会更新下代码

**Comment by Sierkinhane** [comment]
如果要resume一个lr_scheduler，先定义一个lr_scheduler再resume，过段时间我会更新下代码

**Comment by a-whitej** [comment]
optimizer = optim.Adam(
            filter(lambda p: p.requires_grad , model.parameters()),
            lr=config.TRAIN.LR,
        )
        for group in optimizer.param_groups:
            group.setdefault('initial_lr', group['lr'])

在optimizer 代码加入初始化下initial_lr，可以跑起来。
