### ISSUE TITLE
中断续训练的问题

### ISSUE THREAD

**Issue by first-wording** [Sierkinhane/crnn_chinese_characters_rec#234]
你好，由于一些原因我中断了训练，请问如何继续在原先的epoch上继续训练？
例如。在第20个epoch时我中断了训练，得到了40%的准确率，然后更改了FINETUNE_CHECKPOINIT的路径为第20个epoch得到的模型路径，也更该了BEGIN_EPOCH的值为21，但在继训练运行python train.py --cfg lib/config/OWN_config.yaml的时候，虽然显示是从设置的第21个epoch上继续训练，但loss和准确率仍然不是我第20个epoch得到的值，显示loss很大，准确率非常低，并没有继续训练，应该是重新开始了训练，请问除了更改FINETUNE_CHECKPOINIT的路径和BEGIN_EPOCH的值，还需要进行其他的更改么？

**Comment by Sierkinhane** [comment]
TRAIN:
  RESUME:
    IS_RESUME: False
    FILE: ''
改这里

**Comment by first-wording** [comment]
> TRAIN:
> RESUME:
> IS_RESUME: False
> FILE: '
> 改这里

好的，多谢

**Comment by terrynx** [comment]
> TRAIN:
> RESUME:
> IS_RESUME: False
> FILE: ''
> 改这里

你好，续训练已成功。
但是在我用了八万张照片进行训练的时候，准确率最高只有百分之六十左右，我猜测可能是数据集的问题，更换数据集到八十万张图片时，开始训练时报错：
Epoch: [1][1700/178482]	Time 0.012s (0.012s)	Speed 344.8 samples/s	Data 0.001s (0.001s)	Loss 28.69507 (36.92110)	
Epoch: [1][1710/178482]	Time 0.012s (0.012s)	Speed 337.5 samples/s	Data 0.001s (0.001s)	Loss 37.22428 (36.92293)	
Epoch: [1][1720/178482]	Time 0.012s (0.012s)	Speed 334.7 samples/s	Data 0.001s (0.001s)	Loss 42.53692 (36.91513)	
Epoch: [1][1730/178482]	Time 0.011s (0.012s)	Speed 355.8 samples/s	Data 0.001s (0.001s)	Loss 43.09827 (36.92342)	
Epoch: [1][1740/178482]	Time 0.011s (0.012s)	Speed 355.5 samples/s	Data 0.001s (0.001s)	Loss 29.32652 (36.92569)	
Epoch: [1][1750/178482]	Time 0.011s (0.012s)	Speed 351.2 samples/s	Data 0.001s (0.001s)	Loss 43.21587 (36.92159)	
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    main()
  File "train.py", line 137, in main
    function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
  File "/home/terryn/deep_learning/ocr/CRNN_Chinese_Characters_Rec-stable/lib/core/function.py", line 38, in train
    for i, (inp, idx) in enumerate(train_loader): 
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/terryn/.conda/envs/my_torch/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 78, in default_collate
    transposed = zip(*batch)
TypeError: zip argument #3 must support iteration
请问应该如何改正呢？
