### ISSUE TITLE
在服务器上运行train.py 一直无法解决这个问题 是cv的版本不对吗 可以告知下详细的环境配置吗

### ISSUE THREAD

**Issue by Agiroy4712** [Sierkinhane/crnn_chinese_characters_rec#250]
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    main()
  File "train.py", line 135, in main
    function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
  File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/core/function.py", line 36, in train
    for i, (inp, idx) in enumerate(train_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/dataset/_360cc.py", line 45, in __getitem__
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.3.0) /opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by prz30** [comment]
这个是因为你读取的数据的路径里有中文导致的吧，imread不能读取带有中文的路径

**Comment by guomaoqin** [comment]
> Traceback (most recent call last):
> File "train.py", line 160, in
> main()
> File "train.py", line 135, in main
> function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
> File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/core/function.py", line 36, in train
> for i, (inp, idx) in enumerate(train_loader):
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in **next**
> data = self._next_data()
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
> return self._process_data(data)
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
> data.reraise()
> File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
> raise self.exc_type(msg)
> cv2.error: Caught error in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
> data = fetcher.fetch(index)
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/dataset/_360cc.py", line 45, in **getitem**
> img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
> cv2.error: OpenCV(4.3.0) /opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

您好，请问您这个问题解决了吗？我也遇到了相同的问题，请指教。

**Comment by Agiroy4712** [comment]
> 
> 
> > Traceback (most recent call last):
> > File "train.py", line 160, in
> > main()
> > File "train.py", line 135, in main
> > function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
> > File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/core/function.py", line 36, in train
> > for i, (inp, idx) in enumerate(train_loader):
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in **next**
> > data = self._next_data()
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
> > return self._process_data(data)
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
> > data.reraise()
> > File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
> > raise self.exc_type(msg)
> > cv2.error: Caught error in DataLoader worker process 0.
> > Original Traceback (most recent call last):
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
> > data = fetcher.fetch(index)
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/dataset/_360cc.py", line 45, in **getitem**
> > img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
> > cv2.error: OpenCV(4.3.0) /opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
> 
> 您好，请问您这个问题解决了吗？我也遇到了相同的问题，请指教。

您好，我找到了问题的原因是因为数据集的文件没有完全解压，不知道你的是不是。因为当时数据集在服务器上解压，粗心没有仔细看大小，只解压了一部分。所以您可以尝试完全解压数据集后再试试。

**Comment by guomaoqin** [comment]
好的好的。谢谢您。我试试看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liaohaiqing"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 下午4:35
收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 
抄送: "2468734676"<2468734676@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 在服务器上运行train.py 一直无法解决这个问题 是cv的版本不对吗 可以告知下详细的环境配置吗 (#250)





   
Traceback (most recent call last):
 File "train.py", line 160, in
 main()
 File "train.py", line 135, in main
 function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict)
 File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/core/function.py", line 36, in train
 for i, (inp, idx) in enumerate(train_loader):
 File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in next
 data = self._next_data()
 File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
 return self._process_data(data)
 File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
 data.reraise()
 File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
 raise self.exc_type(msg)
 cv2.error: Caught error in DataLoader worker process 0.
 Original Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
 data = fetcher.fetch(index)
 File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/dataset/_360cc.py", line 45, in getitem
 img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 cv2.error: OpenCV(4.3.0) /opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
  
您好，请问您这个问题解决了吗？我也遇到了相同的问题，请指教。
  
您好，我找到了问题的原因是因为数据集的文件没有完全解压，不知道你的是不是。因为当时数据集在服务器上解压，粗心没有仔细看大小，只解压了一部分。所以您可以尝试完全解压数据集后再试试。

**Comment by cendelian** [comment]
> 好的好的。谢谢您。我试试看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liaohaiqing"<notifications@github.com&gt;; 发送时间: 2020年10月27日(星期二) 下午4:35 收件人: "Sierkinhane/CRNN_Chinese_Characters_Rec"<CRNN_Chinese_Characters_Rec@noreply.github.com&gt;; 抄送: "2468734676"<2468734676@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Sierkinhane/CRNN_Chinese_Characters_Rec] 在服务器上运行train.py 一直无法解决这个问题 是cv的版本不对吗 可以告知下详细的环境配置吗 (#250) Traceback (most recent call last): File "train.py", line 160, in main() File "train.py", line 135, in main function.train(config, train_loader, train_dataset, converter, model, criterion, optimizer, device, epoch, writer_dict, output_dict) File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/core/function.py", line 36, in train for i, (inp, idx) in enumerate(train_loader): File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in next data = self._next_data() File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data return self._process_data(data) File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data data.reraise() File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise raise self.exc_type(msg) cv2.error: Caught error in DataLoader worker process 0. Original Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop data = fetcher.fetch(index) File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/mist/CRNN/CRNN_Chinese_Characters_Rec/lib/dataset/_360cc.py", line 45, in getitem img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) cv2.error: OpenCV(4.3.0) /opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor' 您好，请问您这个问题解决了吗？我也遇到了相同的问题，请指教。 您好，我找到了问题的原因是因为数据集的文件没有完全解压，不知道你的是不是。因为当时数据集在服务器上解压，粗心没有仔细看大小，只解压了一部分。所以您可以尝试完全解压数据集后再试试。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问你解决了吗？怎么解决的
我也遇到了一样的问题。
此外，我对对应none的图片拿出来了，图片是OK的，路径也是OK的，就是图片读为none。。。。。。
