### ISSUE TITLE
有关训练时候的多线程问题RuntimeError: DataLoader worker (pid 899) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

### ISSUE THREAD

**Issue by Allen-lz** [Sierkinhane/crnn_chinese_characters_rec#66]
作者您好！请问以下错位如何解决，我用的是Pytorch1.0.0，是否需要使用Pytorch0.4.0才能跑通？
Traceback (most recent call last):
  File "crnn_main.py", line 189, in <module>
    training()
  File "crnn_main.py", line 107, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "crnn_main.py", line 84, in trainBatch
    data = train_iter.next()
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/home/cv_user/anaconda3/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/cv_user/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/cv_user/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/cv_user/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 899) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

**Comment by Sierkinhane** [comment]
有可能是版本问题，1.0可能不太兼容0.4.0以下的版本，

**Comment by Allen-lz** [comment]
谢谢，那我试着改个版本

**Comment by genous110** [comment]
楼主，请问这个问题您解决了吗？我最近也遇到同样的问题？请问您是如何解决的？我的pytorch也是1.0.1版本的。谢谢楼主，我的邮箱号是huzhijuncool@163.com，谢谢赐教

**Comment by Sierkinhane** [comment]
你好，我今晚试了一下代码，可以跑通，pytorch版本是1.0.0，这几天我会利用空闲时间更新一下dataloader部分代码。

**Comment by genous110** [comment]
您好，能跑通是什么意思啊？我的代码在100G的小数据集下面可以跑得很好，但到很大的数据集的时候，这个大数据集有3个多T，就出现问题了，我在4个GPU下面跑代码，运行一个epoch需要一天的时间，偶而可以跑一个epoch不出现问题，但更多的时候是跑了一部分，比如半个epoch，就出现这样的问题。我的代码是每跑完一个epoch就会自动保存模型参数，所以跑完了一个epoch还好，跑不完就得重新加载之前保存的参数再运行，所以我的程序经常是在同一个epoch下面反复的运行。您是怎么解决的？


| |
胡志军
|
|
huzhijuncool@163.com
|
签名由网易邮箱大师定制
在2019年7月22日 22:31，IdleCell.<notifications@github.com> 写道：

你好，我今晚试了一下代码，可以跑通，pytorch版本是1.0.0，这几天我会利用空闲时间更新一下dataloader部分代码。

**Comment by JECULAI** [comment]
So the solution is ?
