### ISSUE TITLE
RuntimeError:CUDNN

### ISSUE THREAD

**Issue by junkojunko** [Sierkinhane/crnn_chinese_characters_rec#74]
Traceback (most recent call last):
  File "/home/ici/Downloads/crnn_chinese_characters_rec-master/crnn_main.py", line 195, in <module>
    training(crnn,train_loader,criterion,optimizer)
  File "/home/ici/Downloads/crnn_chinese_characters_rec-master/crnn_main.py", line 110, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "/home/ici/Downloads/crnn_chinese_characters_rec-master/crnn_main.py", line 94, in trainBatch
    cost = criterion(preds, text, preds_size, length) / batch_size
  File "/home/ici/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ici/.local/lib/python3.5/site-packages/torch/nn/modules/loss.py", line 1248, in forward
    return F.ctc_loss(log_probs, targets, input_lengths, target_lengths, self.blank, self.reduction)
  File "/home/ici/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1732, in ctc_loss
    return torch.ctc_loss(log_probs, targets, input_lengths, target_lengths, blank, _Reduction.get_enum(reduction))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by junkojunko** [comment]
博主你好，我的配置是:1060，内存12g，pytorch 1.0.1 port2，CUDA-9.0,cudnn7.05

**Comment by junkojunko** [comment]
不知道是哪里出了问题，百度后更换版本和删除缓存没有结果，cpu可以运行

**Comment by junkojunko** [comment]
重新装了0.4.1的pytorch，warp_ctc回退到支持0.4.1的版本可以运行了，但是loss降不下来。之前添加了很多字符到alphabet中，其中有9649个字

**Comment by Sierkinhane** [comment]
可以试着调学习率
