### ISSUE TITLE
训练时出现如下错误，请问是什么问题

### ISSUE THREAD

**Issue by tiexizhou** [Sierkinhane/crnn_chinese_characters_rec#99]
Traceback (most recent call last):
  File "crnn_main.py", line 195, in <module>
    training(crnn,train_loader,criterion,optimizer)
  File "crnn_main.py", line 110, in training
    cost = trainBatch(crnn, criterion, optimizer, train_iter)
  File "crnn_main.py", line 85, in trainBatch
    data = train_iter.next()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/na/crnn_new/04_Sierkinhane/crnn_chinese_characters_rec-master/dataset.py", line 50, in __getitem__
    buf.write(imgbuf)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by Sierkinhane** [comment]
Nonetype，没有成功读取文件，检查一下图片路径

**Comment by Tian14267** [comment]
@tiexizhou 请问你这个问题解决了吗？我也遇到这个问题了，但是制作的lmdb文件都是正常的。
